ktor:
    application:
        modules:
            - com.detivenc.github.ktordocker.ApplicationKt.module
    deployment:
        port: 8080
        host: 0.0.0.0

database:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
