ktor:
  application:
    modules:
      - ApplicationKt.module
  deployment:
    port: 8080

jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"

database:
  url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
  driver: "org.h2.Driver"
  user: "sa"
  password: ""

ai:
    lmstudio:
        url: "http://127.0.0.1:1234"
        apiKey: "lm-studio"
        model: "openai/gpt-oss-20b"
    systemPrompt: "You are a helpful assistant."